### ISSUE TITLE
does not work in python 3.13

### ISSUE THREAD

**Issue by mke21** [jwlodek/py_cui#187]
In python 13, py_cui does not work because of changes in the logging module.

```
AttributeError: module 'logging' has no attribute '_acquireLock'
```

**Comment by jwlodek** [comment]
I will try and get around to publishing a new release this weekend, thanks for the reminder!

**Comment by wilsonmcdade** [comment]
Hi, is there any update on this? Thanks!

**Comment by wilsonmcdade** [comment]
Just checking in about 3.14 support :)
